feat: 지도 컴포넌트, 메인메뉴
sim-co/daisy-frontend-flutter pull request #2
Opened 2023-03-30 16:47 UTC by olivyou2

# 지도컴포넌트
## 마커
마커 클래스 추가. 조금 더 추상화가 필요함
## 패스
길 찾는 API 가 필요할 것 같음. 그냥 마커끼리 이으면 알아서 길찾기 될 줄 알았는데 아니였나봅니다. 이부분은 어떻게 잘 처리 해봐야 할듯.
## 필터
필터 버튼 추가. 아직 기능 없음
### 데이트 지도 만들기 시트
이 부분은 개발 필요

# 메인메뉴
## 디스크립션
각 데코레이션 위에 설명 위젯
## 데코레이션
각 메뉴에 데코레이션 이라는 이름을 붙였는데, 종류에 따라 여러 클래스를 만들 수 있을듯
### 와이드 데코레이션
메인메뉴 상단에 노출되는 데코레이션 위젯, 커스터마이징 할 수 있게 만들어야 할 듯
### 하프위드 데코레이션
가로사이즈 반 차지하는 데코레이션 위젯

2023-04-01 17:33 UTC, BHyeonKim requested changes
고생하셨습니다!🥹

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/atom/button.dart
> +  void onClickButton(details) {
여기 파라미터로 details은 왜 받는거죠?

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/atom/decoration/halfWidthDecoration.dart
> +  Color? backgroundColor;
```
  final double height;
  final Text? overlayText;
  final Text? subOverlayText;
  final Widget? textTopWidget;
  final Widget? overlayWidget;

  final Color? backgroundColor;

  const HalfWidthDecoration({
    super.key,
    this.backgroundColor,
    this.overlayText,
    this.subOverlayText,
    this.textTopWidget,
    required this.height,
    this.overlayWidget,
  });
```
이렇게 바꿔야 하지 않을까요?

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/atom/decoration/wideDecoration.dart
> +import 'package:widget_mask/widget_mask.dart';
안쓰는 import 제거 필요

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/atom/decoration/wideDecoration.dart
> +import 'package:daisy_frontend/util/color.dart';
안쓰는 import 제거 필요

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/atom/description.dart
> +  late String description;
이거 왜 late로 했어요?
단순 궁금

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/atom/map.dart
> +import 'dart:ffi';
안쓰이는 package라고 뜨네요

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/atom/profileImage.dart
파일이름 카멜케이스가 아니라 스네이크 케이스로 바꾸는게 좋지 않을까요?

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/molecule/courseSheet.dart
> +import 'dart:convert';
안쓰이는 import

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/molecule/courseSheet.dart
> +import 'mapTopIndicator.dart';
안쓰이는 import

2023-04-01 17:33 UTC, BHyeonKim commented on lib/main/widgets/molecule/mapTopIndicator.dart
> +import '../../../util/color.dart';
안쓰이는 import

2023-04-08 20:51 UTC, olivyou2 commented on lib/main/widgets/atom/button.dart
> +  void onClickButton(details) {
onTapUp 의 콜백이라서 그렇습니당

2023-04-08 20:55 UTC, olivyou2 commented on lib/main/widgets/atom/description.dart
> +  late String description;
아마 뇌빼고 코딩하다가 이유없이..

2023-04-08 20:56 UTC, olivyou2 commented on lib/main/widgets/atom/profileImage.dart
이거 나중에 한번에 바꾸져

2023-04-09 04:07 UTC, BHyeonKim approved these changes
고생하셨소다

2023-04-09 04:09 UTC, merged